### ISSUE TITLE
Xcode 8下编译，只能在iOS9.3以上运行正常

### ISSUE THREAD

**Issue by Michaelyb520** [forkingdog/FDFullscreenPopGesture#101]
Xcode 8下编译，只能在iOS9.3以上运行正常，iOS9.3以下直接crash，崩掉了！！！！

**Comment by Michaelyb520** [comment]
Xcode 7.3编译，在iOS各个版本都能很好的运行！

**Comment by afantree** [comment]
Is it solved now ?

**Comment by afantree** [comment]
Are you sure? I run the demo on both simulator( iOS 8.4 12H143 ) and iPod(iOS 8.4 12H143) use Xcode 8 .😛
Thanks !
