### ISSUE TITLE
无法禁用

### ISSUE THREAD

**Issue by CeoRain** [forkingdog/FDFullscreenPopGesture#104]
我在某个vc里禁用了，但是仍然无效

**Comment by ganjmeng** [comment]
我也想禁用，用他提供的那个方法也没有用，请问你现在解决了吗

**Comment by bairdweng** [comment]
问题+1.如何禁用？

**Comment by bairdweng** [comment]
我解决了，参考下，写一个单利作为开关。在fd_viewWillAppear，fd_pushViewController，fd_setupViewControllerBasedNavigationBarAppearanceIfNeeded。YES/NO决定代码是否往下执行。
![d24c4470-18cc-473d-beb2-ebaa96c773bd](https://cloud.githubusercontent.com/assets/8598304/20516148/05aa96aa-b0d0-11e6-8adf-c4fb599aff11.png)
