### ISSUE TITLE
导航栏按钮点击反应迟钝

### ISSUE THREAD

**Issue by JamhonyZ** [forkingdog/FDFullscreenPopGesture#105]
最近产品要求解决导航条按钮点击反应迟钝问题，找了很久的原因 发现去掉FDFullscreenPopGesture 这个东西，反应就灵敏多了！导航按钮 都是UIButton 赋作 UIBarButtonItem , 在这里留言望指导。

**Comment by wfxiaolong** [comment]
不可能！上代码，没准你自己的代码里边加了其他的手势有影响？
不过我发现了一个新的问题：
就是present一个navigationVC的时候，这样写是有问题的...
    MFMessageComposeViewController *controller = [[MFMessageComposeViewController alloc] init];
    controller.body = NSLocalizedString(@"I found this bug for the fd_navigationBar.", nil);
    controller.messageComposeDelegate = self;
    [self presentViewController:controller animated:YES completion:^{
    }];
