### ISSUE TITLE
请问,如果我使用了UIPageViewController,如何增加一个返回pop的手势呢?

### ISSUE THREAD

**Issue by ws4715535** [forkingdog/FDFullscreenPopGesture#107]
请问,如果我使用了UIPageViewController,如何增加一个返回pop的手势呢?  貌似有冲突?

**Comment by afantree** [comment]
Do you have try to overload the gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: method for conflict ?
https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview
