### ISSUE TITLE
请问能否支持阿拉伯语,就是左右界面全完颠倒

### ISSUE THREAD

**Issue by XHJiang** [forkingdog/FDFullscreenPopGesture#109]
接入完全无效了...

**Comment by afantree** [comment]
Arabic ....   
Can you pull a request into the FDFullscreenPopGesture for Arabic ?
Thanks !

**Comment by XHJiang** [comment]
I can`t

**Comment by afantree** [comment]
@XHJiang  hello，#138   for Arabic 
Thanks @ichina
