### ISSUE TITLE
当项目中用了KINWebBrowserViewController这个第三方后

### ISSUE THREAD

**Issue by yanglezyq** [forkingdog/FDFullscreenPopGesture#111]
如果控制器A，隐藏导航条，设置了 `self.fd_prefersNavigationBarHidden = YES;`
push到控制器B，B中有KINWebBrowserViewController ，此时如果用手往右侧滑动B一丢丢，快速的松手，此时的导航条会在 隐藏/显示 间不断的切换。

KINWebBrowserViewController 中部分代码如下：
`
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    [self.navigationController setNavigationBarHidden:NO animated:YES];
    [self.navigationController setToolbarHidden:YES animated:YES];
    
    [self.navigationController.navigationBar addSubview:self.progressView];
    
    [self updateToolbarState];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    [self.navigationController setNavigationBarHidden:self.previousNavigationControllerNavigationBarHidden animated:animated];
    
    [self.navigationController setToolbarHidden:self.previousNavigationControllerToolbarHidden animated:animated];
    
    [self.uiWebView setDelegate:nil];
    [self.progressView removeFromSuperview];
}
`

作者有时间可以看下～

**Comment by DolphinQuan** [comment]
我也出现这个问题 A和B都继承基类

**Comment by afantree** [comment]
恩，readme 里面写的 

> This opmiziation is enabled by default, from now on you don't need to call UINavigationController's -setNavigationBarHidden:animated: method 

你设置fd_prefersNavigationBarHidden API之后，不需要在自己手动的setNavigationBarHidden，

这个与KINWebBrowserViewController设置冲突了。

**Comment by afantree** [comment]
有一个处理冲突的方法。
A 继承KINWebBrowserViewController ，然后在A类里面的viewWillAppear方法
`
-(void)viewWillAppear:(BOOL)animated {
~~[super viewWillAppear:animated];~~

~~[self.navigationController setNavigationBarHidden:NO animated:YES];~~
~~[self.navigationController setToolbarHidden:YES animated:YES];~~
~~[self.navigationController.navigationBar addSubview:self.progressView];~~

[self updateToolbarState];
}
`
把画删除线的都删除了，应该就解决了。
利用OOP的override机制。

**Comment by yanglezyq** [comment]
按照上述办法，并不能解决该问题。

**Comment by DolphinQuan** [comment]
我这里是A设置了UIStatusBarStyle.lightContent 的问题。时如果用手往右侧滑动B一丢丢，会调用A的override var preferredStatusBarStyle: UIStatusBarStyle。
如果设置为default则不会出现这个导航条会在 隐藏/显示 间不断的切换。但是没发在A的statusBar设置为light
