### ISSUE TITLE
严重bug：当我从二级页面像右边滑动回来的时候，整个导航栏整体像左偏移，并且还会变模糊

### ISSUE THREAD

**Issue by WoAiLiMoChou** [forkingdog/FDFullscreenPopGesture#113]
当我从二级页面像右边滑动回来的时候，整个导航栏整体像左偏移，并且还会变模糊，但是位置看起来发生变化了，事实上点击效果任然在中间，我中间设置的titleView，titleView上面两个按钮，点击效果啥的都没有变，点击的位置也在中间，只是看起来导航栏偏移了向左，并且还模糊了，这是啥情况！急急急

**Comment by Hext123** [comment]
同样的问题, 发现在iOS 10.3 上, 滑动返回时nav会抖, 滑动太快时导航栏还会动画卡住

![](http://i4.buimg.com/567571/fce385da64d49785.gif)

**Comment by WoAiLiMoChou** [comment]
有什么好的解决方案吗

**Comment by jaoye** [comment]
这个问题 怀疑 是 新版 Xcode 导致，不用这个库 也会导致这个问题。你们怎么解决的。 @WoAiLiMoChou @Hext123

**Comment by sunjianan** [comment]
这个是系统的bug
