### ISSUE TITLE
页面上有slider，如果避免手势冲突

### ISSUE THREAD

**Issue by aslanTT** [forkingdog/FDFullscreenPopGesture#115]
rt

**Comment by newjia** [comment]
View Controller With ScrollView

If you want to use fullscreen pop gesture in ViewController with scrollView or subclass of scrollView , you should customize the scrollView or subclass of scrollView and overload the gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: method . like this:


给Scrollview 添加分类，添加方法如下

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    if (self.contentOffset.x <= 0) {
        if ([otherGestureRecognizer.delegate isKindOfClass:NSClassFromString(@"_FDFullscreenPopGestureRecognizerDelegate")]) {
            return YES;
        }
    }
    return NO;
}

**Comment by newjia** [comment]
新建Scrollview 分类。这是 .h

@interface UIScrollView (FDScroll)

@end


这是 .m.  
#import "UIScrollView+FDScroll.h"
#import "UINavigationController+FDFullscreenPopGesture.h"
@implementation UIScrollView (FDScroll)

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    if (self.contentOffset.x <= 0) {
        if ([otherGestureRecognizer.delegate isKindOfClass:NSClassFromString(@"_FDFullscreenPopGestureRecognizerDelegate")]) {
            return YES;
        }
    }
    return NO;
}
@end


重新运行即可解决问题！！！！

**Comment by aslanTT** [comment]
@newjia  谢谢

**Comment by Takeroro** [comment]
如果这个UISlider  只是加在 view 上面，而不是 scrollView， 这样 UISlider 跟  UIScrollView 没有任何联系了吧？为啥建个 UIScrollView 可以解决？
