### ISSUE TITLE
A -> B  如果隐藏A导航栏并把状态栏颜色改成UIStatusBarStyleLightContent,B不隐藏且不不更改状态栏颜色,从B手势返回时候可能造成B的导航栏隐藏

### ISSUE THREAD

**Issue by Chenchening** [forkingdog/FDFullscreenPopGesture#116]
A控制器
- (UIStatusBarStyle)preferredStatusBarStyle
{
    return UIStatusBarStyleLightContent;
}

当B全屏返回失败的时候会造成B的导航栏也隐藏掉

**Comment by tengshuq** [comment]
同遇到这个问题。。请问解决了没有

**Comment by Chenchening** [comment]
终于解决了...
在InfoPlist里面把View controller-based status bar appearance 设置为NO,让Application来控制statusBar的颜色状态就不会出现这个bug了.

这个应该是系统的bug,因为如果是系统的手势,用控制器来控制statusBar的颜色也会出现这个bug.

**Comment by XDB-Chang** [comment]
@Chenchening 除了这个方法就没有别的方法了吗?有没有其他的办法呀？

**Comment by sunjianan** [comment]
#121
