### ISSUE TITLE
A -> B 如果隐藏A导航栏并把状态栏颜色改成UIStatusBarStyleLightContent,B不隐藏且不不更改状态栏颜色,从B手势返回时候可能造成B的导航栏隐藏

### ISSUE THREAD

**Issue by XDB-Chang** [forkingdog/FDFullscreenPopGesture#121]
A -> B 如果隐藏A导航栏并把状态栏颜色改成UIStatusBarStyleLightContent,B不隐藏且不不更改状态栏颜色,从B手势返回时候可能造成B的导航栏隐藏

**Comment by XDB-Chang** [comment]
不希望通过更改info的方法

**Comment by wxh794708907** [comment]
在A控制器中隐藏导航栏 B控制器中viewWillAppear中显示导航栏 这种情况下 如果只滑动一点松手会出现导航栏被隐藏的问题 ，你有没有解决方案啊 我至今没找到好的解决方案 望解答啊

**Comment by wayone** [comment]
遇到这个问题了，求解

**Comment by XDB-Chang** [comment]
在InfoPlist里面把View controller-based status bar appearance 设置为NO,让Application来控制statusBar的颜色状态就不会出现这个bug了.

这个应该是系统的bug,因为如果是系统的手势,用控制器来控制statusBar的颜色也会出现这个bug.


看需要是否可以采用这个方法吧

**Comment by sunjianan** [comment]
最新版已经修复，#55 中有提到解决方案

**Comment by sunjianan** [comment]
这个是系统bug，使用 preferredStatusBarStyle 在右滑返回会有动画效果，当动画没有执行完毕的时候取消右滑就会导致bar消失。
