### ISSUE TITLE
UIBarStyleBlack 导航栏切换BUG

### ISSUE THREAD

**Issue by siperman** [forkingdog/FDFullscreenPopGesture#123]
前提：当程序设置了 [[UINavigationBar appearance] setBarStyle:UIBarStyleBlack] 时
1.从无导航vc push到有导航
2.稍微向右滑动，然后松手
3.导航栏会消失，再试又会显示

**Comment by ziyanliu** [comment]
解决办法在有导航的那个VC的viewWillAppear加上
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(CGFLOAT_MIN * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    UIViewController *vc = [self.navigationController.viewControllers lastObject];
    if (vc.fd_prefersNavigationBarHidden) {
        [self.navigationController setNavigationBarHidden:YES animated:NO];
    } else {
        [self.navigationController setNavigationBarHidden:NO animated:NO];
    }
});

**Comment by sunjianan** [comment]
#55
