### ISSUE TITLE
与UIPageViewController滑动冲突

### ISSUE THREAD

**Issue by nierongcheng** [forkingdog/FDFullscreenPopGesture#125]
如果在项目中使用了FDFullscreenPopGesture，UIPageViewController滑动推出手势就不起作用了，无论是否关闭了UIViewController或UINavigationController都没有效果。

**Comment by sunjianan** [comment]
#107

**Comment by MrCaiWH** [comment]
@sunjianan @nierongcheng 这个方法你们用着有效？我这没有效果，不知道为什么
