### ISSUE TITLE
侧滑返回当前页时 跑马灯效果文字就停止滚动了

### ISSUE THREAD

**Issue by lihuichina** [forkingdog/FDFullscreenPopGesture#134]
侧滑返回当前页时 跑马灯效果滚动的label 有时就停止滚动了 怎么解决？

**Comment by afantree** [comment]
在`- (void)viewWillAppear:(BOOL)animated`和`- (void)viewWillDisappear:(BOOL)animated`中开启和关闭滚动的label？试试？

**Comment by afantree** [comment]
有问题就在这儿反馈吧。。。我先关了
