### ISSUE TITLE
ios 10.3以后 出现 ios7 导航栏手势返回 显示异常 的问题 并且滑动结束后 有时候还抖动一下

### ISSUE THREAD

**Issue by mengzhou2014** [forkingdog/FDFullscreenPopGesture#137]
ios 10.3以后 出现
 ios7 导航栏手势返回 显示异常 的问题
 并且滑动结束后 有时候还抖动一下
正常
![image](https://user-images.githubusercontent.com/7875765/26861621-9b614d0a-4b77-11e7-929b-de031130c51c.png)
异常
![image](https://user-images.githubusercontent.com/7875765/26861604-829ae506-4b77-11e7-9505-bb69a51f1a69.png)
还有侧滑结束后 左右抖动一下。
9.3以前的都没问题，请问怎么解决一下

**Comment by sunjianan** [comment]
系统bug，滑动快了之后会出现这个问题
