### ISSUE TITLE
presentViewController MFMessageComposeViewController整个导航栏都为空白了

### ISSUE THREAD

**Issue by CocoaDebug** [forkingdog/FDFullscreenPopGesture#14]
大大, 我发现FDFullscreenPopGesture一个bug, 就是导入后当我要present MFMessageComposeViewController时, 以外发现发短信页面的导航栏全是白的, 原来的title和cancel按钮都不见了...求指点 QQ723661989 谢谢!!

**Comment by wuminglan** [comment]
一个临时的解决方法，
- (void)fd_pushViewController:(UIViewController *)viewController animated:(BOOL)animated
{
//添加这句 
    if ([self isKindOfClass:[MFMessageComposeViewController class]]) {
        [self fd_pushViewController:viewController animated:animated];
        return;
    }
    ......
}

**Comment by xiafb** [comment]
请问这个问题解决了吗，我这里同样的问题还是存在。

**Comment by hstdt** [comment]
@wuminglan 的方法可行
稍微优化了一下,就不用多导入类了
 [self isKindOfClass:NSClassFromString(@"MFMessageComposeViewController")]

**Comment by sunlymaster** [comment]
@wuminglan ,我用你这个方法，直接奔溃掉了!崩溃信息是*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing the same view controller instance more than once is not supported (<CKSMSComposeController: 0x1b89e600>)'

**Comment by likers** [comment]
@sunlymaster 你应该把过滤的代码放在`(void)fd_pushViewController:(UIViewController *)viewController animated:(BOOL)animated` 的最开始，这样就会直接return

**Comment by xxdzyyh** [comment]
if ([viewController isKindOfClass:NSClassFromString(@"CKSMSComposeController")]) {
        
        [self fd_pushViewController:viewController animated:animated];
        
        return;
    }

**Comment by caoway** [comment]
ios10 下面这个解决方法也没用了 还有什么其他解决办法吗

**Comment by likers** [comment]
用原生的interactivePopGestureRecognizer吧
