### ISSUE TITLE
返回手势有bug

### ISSUE THREAD

**Issue by Feb-Red** [forkingdog/FDFullscreenPopGesture#149]
tabar上的是一个隐藏导航啦的导航控制器，push到有导航栏的下一级，然后侧滑很小的距离，然后取消，这是，当前控制器的导航栏被隐藏了，重复此动作，会发现，会发现当前控制器的导航栏会一直在隐藏、不隐藏之间切换

**Comment by sunjianan** [comment]
#55    系统bug。    不要导入pod版本，直接下载最新的代码
