### ISSUE TITLE
UITableViewCell 上有输入框时, 当键盘弹出时, 滑动返回出现tableView下移.键盘不弹出时则正常

### ISSUE THREAD

**Issue by CXTretar** [forkingdog/FDFullscreenPopGesture#151]
![331503973969_ pic](https://user-images.githubusercontent.com/17959278/29802174-4d2cf970-8ca6-11e7-8d9a-92beba2c4cfc.jpg)

**Comment by dwade333** [comment]
出现同样的问题 ，问问怎么解决的

**Comment by wv-y** [comment]
你是使用了IQKeyboardManager吗？我也遇到了同样的问题，二者同时使用就会有这个问题
