### ISSUE TITLE
iOS11侧滑返回第一个控制器上会闪一个跟导航栏差不多高的白条

### ISSUE THREAD

**Issue by shasha7** [forkingdog/FDFullscreenPopGesture#154]

**Comment by yigegongjiang** [comment]
我也是，希望有方案

**Comment by vvkeep** [comment]
求解

**Comment by shasha7** [comment]
貌似是因为二级页面带有scollview或者其子类，都会产生问题

**Comment by xuchaofei** [comment]
这个是IOS 11中的scrollView的automaticallyAdjustsScrollViewInsets的废弃导致的,使用下面的方法替换掉        self.automaticallyAdjustsScrollViewInsets = NO 就OK了
    
if (@available(iOS 11.0, *)) {
 
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
 
    } else {
 
        self.automaticallyAdjustsScrollViewInsets = NO;
 
    }



 
    




------------------ 原始邮件 ------------------
发件人: "shasha7";<notifications@github.com>;
发送时间: 2017年9月26日(星期二) 下午4:28
收件人: "forkingdog/FDFullscreenPopGesture"<FDFullscreenPopGesture@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [forkingdog/FDFullscreenPopGesture] iOS11侧滑返回第一个控制器上会闪一个跟导航栏差不多高的白条 (#154)




貌似是因为二级页面带有scollview或者其子类，都会产生问题

**Comment by shasha7** [comment]
非常感谢您的回复。但是这段代码已经写过了，这个只能将状态栏高度调整为合适的高度，从二级页面POP回来白条还是会闪。不是一个20pt的留白，是一个差不多64pt～84pt的半透明bar，会闪现一下。只有侧滑返回会出现这个问题。

**Comment by shasha7** [comment]
@xuchaofei 非常感谢您的回复，但是这段适配代码已经加过了。我的问题并不是会有留白，而是侧滑返回的时候会有一个64pt左右的半透明bar闪一下。另外还有一个奇怪的问题，有的页面直接POP回来，当前控制器会有20pt的黑条，这都是在我写过适配代码之后出现的问题。

**Comment by mengkeer** [comment]
我也遇到了 求解  但是我遇到的页面并没有scollview或者其子类，还是遇到了   @shasha7

**Comment by mengkeer** [comment]
我这边的情况是两个页面都是隐藏导航栏的  用的是  self.fd_prefersNavigationBarHidden = NO;然后push过程中就出现问题了，push时出现会闪和导航栏高度差不多的白条

然后我添加了一句   self.navigationController.navigationBar.hidden = YES;解决了

即同时用系统的API和这个库的API隐藏这个导航栏，如果你们的情况和我类似的话，可以试试

**Comment by shasha7** [comment]
@mengkeer 非常感谢您提供的方案，请问您的这句隐藏的代码是在什么时机添加的呢，直接修改的类别么。可否请您详细解释一下，非常感谢

**Comment by mengkeer** [comment]
@shasha7  
如果你的页面需要隐藏导航栏的话，在viewDidLoad里添加如下两句代码
    self.navigationController.navigationBar.hidden = YES;
    self.fd_prefersNavigationBarHidden = YES;
其中第二行是这个第三方库的代码，需要导入这个第三方库，另外请移除其它显示或隐藏导航栏的代码
我就是这样解决了，希望能帮助到你
当然如果你的情况和我不一样的话，可能需要寻找另外的解决方法

**Comment by Liqiankun** [comment]
这个库貌似没人维护了？

**Comment by Liqiankun** [comment]
这个问题有没有解决方案现在，我的是在PUSH的时候有问题，NavigationBar上会有白条！

**Comment by afantree** [comment]
#159 是不是出现了这个issue上面说的问题 
另，有没有Demo可以给我复现一下？ @shasha7

**Comment by Liqiankun** [comment]
我也遇到这个问题但不是这个库造成的！我的是[KMNavigationBarTransition](https://github.com/MoZhouqi/KMNavigationBarTransition)造成的.[IOS11 navigationBar height changes when push](https://github.com/MoZhouqi/KMNavigationBarTransition/issues/99) @shasha7 @adronfan @mengkeer @xuchaofei @afantree

**Comment by afantree** [comment]
@Liqiankun 赞一个，这个库一直有人维护的

**Comment by biyuhuaping** [comment]
找了半天资料，终于完美解决：
加入下面一句代码就可以了。
`- (void)viewDidLoad {
    ……
    self.extendedLayoutIncludesOpaqueBars = YES;
    ……
}`

**Comment by yangzheng006** [comment]
我也遇到了这个问题，改不了了

**Comment by biyuhuaping** [comment]
有列表情况时，侧滑过程中，怎么禁止列表上下滑动呢？
