### ISSUE TITLE
连着Push两个NavigationBarHidden的ViewController之后出现BUG

### ISSUE THREAD

**Issue by lovesunstar** [forkingdog/FDFullscreenPopGesture#16]
1、push一个ViewController，hideNavigationBar
2、push一个ViewController，hideNavigationBar
3、右滑触发返回手势，不要完全返回，左滑取消返回手势
4、正常滑动返回两个ViewController
5、任意Push一个ViewController，发现NavigationBarItem为viewControllers[0]的NavigationBarItem

另外，早上无意发现另一种方法。。。
NavigationController中直接使用
object_setClass(self.interactivePopGestureRecognizer, [UIPanGestureRecognizer class]); 即可

BUG如下图所示。。当然这个直接使用系统的也会有问题

![navigationbug_2](https://cloud.githubusercontent.com/assets/2378280/8300618/3942e166-19b9-11e5-8b2d-53eea3947d64.gif)

**Comment by sunnyxx** [comment]
这个可能是系统实现函数自己的bug，不是很好解决

**Comment by lovesunstar** [comment]
应该是navigationBarHidden/重新指定navigationItem.leftBarButtonItem的时候没有效果，这个最左侧滑动也是一样的，指定delegate就OK了。

```
Class XXNavigationController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    object_setClass(self.interactivePopGestureRecognizer, [UIPanGestureRecognizer class]);
    self.interactivePopGestureRecognizer.delegate = self;
}

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    return self.viewControllers.count > 1;
}

```

**Comment by mumuda** [comment]
你好，无遇到同样的问题，请问你们是如何解决的～

**Comment by Zkim** [comment]
override public func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        if self.isMovingFromParentViewController(){
            if ((self.navigationController?.delegate = self) != nil){
                self.navigationController?.delegate = nil
            }
        }
    }

for swift

**Comment by VaeXnn** [comment]
把那个写在viewdidload里面,别写在viewwillappear




------------------ 原始邮件 ------------------
发件人: "Aden";<notifications@github.com>;
发送时间: 2016年7月18日(星期一) 中午12:16
收件人: "forkingdog/FDFullscreenPopGesture"<FDFullscreenPopGesture@noreply.github.com>; 

主题: Re: [forkingdog/FDFullscreenPopGesture] 连着Push两个NavigationBarHidden的ViewController之后出现BUG (#16)




override public func viewWillDisappear(animated: Bool) {
         super.viewWillDisappear(animated)
         if self.isMovingFromParentViewController(){
             if ((self.navigationController?.delegate = self) != nil){
                 self.navigationController?.delegate = nil
             }
         }
     }
 
for swift

**Comment by Zkim** [comment]
viewdidload是去设置delegate ,并且按照你说的我试了一下还是会crash，只能写再disappear,你能说下你的理由？

**Comment by CoderJackie** [comment]
这个问题没有解决就关闭了吗？
