### ISSUE TITLE
iOS 11上向右滑一半但不返回上一页面，可能出现导航栏返回按钮消失

### ISSUE THREAD

**Issue by jiabibi888** [forkingdog/FDFullscreenPopGesture#160]
iOS 11系统下，所有页面，向右滑一半但不返回上一页面，多次后可能出现导航栏按钮消失，但仍可通过右滑返回
请问是什么原因，有解决办法吗

**Comment by xiaobing1024** [comment]
+1，我说一下我这边的情况，如果使用『系统提供』的『返回按钮』是不会出现这种情况，如果『上一页面是用 `fd_prefersNavigationBarHidden` 隐藏了 `navbar` 也不会出现』。
当我用自己 `leftBarButtonItem` 做为返回按钮，只要右拉一些，不返回。就会让我的返回按钮消失

**Comment by AKIRACW** [comment]
同样的情况，A隐藏导航栏，B显示导航栏，在B页面向右滑动一点但不返回A，会导致B的导航栏消失。

**Comment by Mephsito23** [comment]
喜极而泣,我还以为就我一个遇到这样的情况,通过一晚上的测试,我发现如果将自定义leftBarButtonItem的代码从 viewDidLoad中转移到viewWillAppear中貌似可以解决问题,但是这样的话相当于每次刷新页面都会创建新的按钮,感觉并不是完美的解决方案

**Comment by Desperoid** [comment]
我也遇到这个问题；但不是必现，有解决方法么？

**Comment by afantree** [comment]
#159 使用这个issue上面说的库了吗？有没有demo给发过来看看

**Comment by afantree** [comment]
#154 老铁们，应该遇到的是同一个问题。

**Comment by waynett** [comment]
遇到同样问题

**Comment by wongwenlei** [comment]
有解决办法吗，自定义的导航栏，在连续push两次之后会发生这种情况

**Comment by beautive** [comment]
同上问题，能解决么？

**Comment by a330416020** [comment]
我这边不是使用这个库的问题，在IOS 11上把UIBarButtonSystemItemFixedSpace 这个设置按钮的space方法给干掉就解决我这边的问题了。
	if (self.navigationController.viewControllers.count > 1) {
		UIBarButtonItem *space = [TSHUIBarButtonTypeUtility navBarButtonItemWithFixedSpace:-16];
		UIBarButtonItem *backItem = [[UIBarButtonItem alloc] initWithCustomView:btn];
        
        if (@available(iOS 11.0, *)) {
            self.navigationItem.leftBarButtonItems = @[backItem];
        }else {
            self.navigationItem.leftBarButtonItems = @[space, backItem];
        }
	}
