### ISSUE TITLE
FDFullscreenPopGesture有什么办法能直接返回到根控制器吗

### ISSUE THREAD

**Issue by MrCaiWH** [forkingdog/FDFullscreenPopGesture#162]
FDFullscreenPopGesture有什么办法能直接返回到根控制器吗?比如说栈里有三个控制器，现在想直接返回到根控制器，可以实现吗？

**Comment by CoderDHT** [comment]
在c控制器中将b控制器从栈里移除就可以直接回到a控制器了~\(≧▽≦)/~啦啦啦
