### ISSUE TITLE
今天 APP 被拒了，说使用了私有 API : PrivateFrameworks/ChatKit.framework￼

### ISSUE THREAD

**Issue by LisonFan** [forkingdog/FDFullscreenPopGesture#171]
`ChatKit.framework￼`里的头文件基本上都是`CK`开头的，我就使用命令行搜整个项目文件发现 `FDFullscreenPopGesture`使用了`if ([viewController isKindOfClass:NSClassFromString(@"CKSMSComposeController")]) `难道是因为这个判断的原因导致被拒的？

**Comment by LisonFan** [comment]
真是这个原因....

**Comment by Wuou** [comment]
与这个框架有毛关系。

**Comment by LisonFan** [comment]
@Wuou 注释了```if ([viewController isKindOfClass:NSClassFromString(@"CKSMSComposeController")])```就过了

**Comment by Wuou** [comment]
PrivateFrameworks/ChatKit.framework￼   你这个ChatKit.framework￼ 第三方聊天框架的问题，应该是这个框架使用了私有api
