### ISSUE TITLE
UIBarButtonItem会消失。 导航栏设置leftBarButtonItems 如果其中包含了UIBarButtonSystemItemFixedSpace类型

### ISSUE THREAD

**Issue by WaaaaaghBoss** [forkingdog/FDFullscreenPopGesture#174]
系统是ios11.1.2

就会出现拖动后送开（稍微拖动一下，不会触发返回的那种），多试几次就会出现，并不是每次都有，然后导航栏的leftBarButtonItems就不显示了

![1](https://user-images.githubusercontent.com/11940269/37275943-79cb73da-261b-11e8-8aa8-6b251a9c5b4d.png)

![2](https://user-images.githubusercontent.com/11940269/37275976-85fba832-261b-11e8-9a60-6b7ebbdcb942.png)

图1和图2注意看左边的结构，图2就是拖动一下然后松开，“cs”按钮就不见了
但是看到内存中是有的，但是ownerview变为了nil

**Comment by xiaoer371** [comment]
我也遇到了～ 参考  #160

**Comment by 964562398** [comment]
我是在ios11中去掉UIBarButtonSystemItemFixedSpace就可以了

**Comment by WaaaaaghBoss** [comment]
@xiaoer371 对的在ios11中去掉UIBarButtonSystemItemFixedSpace就ok了
