### ISSUE TITLE
遇到的问题

### ISSUE THREAD

**Issue by lyxia** [forkingdog/FDFullscreenPopGesture#18]
当设置了navigationitem.leftBarButtonItem后还能滑动pop，ios自带的是不能的

![image](https://cloud.githubusercontent.com/assets/7269593/8373258/aad730d2-1c1d-11e5-9e28-2636ef732ce7.png)

**Comment by afantree** [comment]
这个库的目的就是改变原生系统的滑动方法，你这个issue的目的是说明什么？

**Comment by TheLittleBoy** [comment]
@afantree 本来当你设置了leftbarbuttonitem以后，系统的侧边返回手势是失效的。但是，用了本代码以后，手势还是可以用的。 我觉得这种情况，只能去自己添加代码 viewController.fd_interactivePopDisabled = YES;  去手动控制了。
