### ISSUE TITLE
求解惑

### ISSUE THREAD

**Issue by changsanjiang** [forkingdog/FDFullscreenPopGesture#183]
大神, 我有两点疑惑.如下:

1. load方法中替换`pushViewController:animated:`时, 在[此处](https://github.com/forkingdog/FDFullscreenPopGesture/blob/44ddc103fd7ce7ffd5250b5a39ee69aca4465c95/FDFullscreenPopGesture/UINavigationController%2BFDFullscreenPopGesture.m#L148)为什么需要调用`class_replaceMethod `...

2. 如果`class_replaceMethod`执行了, 而`fd_pushViewController:animated:`方法中会调用自己, 岂不是造成无限循环啦?

**Comment by JazzPC** [comment]
1. 调用class_replaceMethod 函数是为了将这两个函数的函数指针就行调换，调换后系统的函数指针指向了你自己编写的函数，而你自己编写的函数指针指向了系统的函数
2. 因为两个函数的指针互相调换了 所以在fd_pushViewController:animated:中调用自己其实是调用了系统的函数




发自网易邮箱大师


在2018年07月9日 15:41，changsanjiang<notifications@github.com> 写道：

大神, 我有两点疑惑.如下:

load方法中替换pushViewController:animated:时, 在此处为什么需要调用class_replaceMethod...

如果class_replaceMethod执行了, 而fd_pushViewController:animated:方法中会调用自己, 岂不是造成无限循环啦?

**Comment by changsanjiang** [comment]
谢谢你的回答, 我被绕晕了, 刚刚看懂了😆

**Comment by JazzPC** [comment]
不客气




发自网易邮箱大师


在2018年07月9日 15:47，changsanjiang<notifications@github.com> 写道：

谢谢你的回答, 我被绕晕了, 刚刚看懂了😆
