### ISSUE TITLE
  iOS 14设置 self.fd_prefersNavigationBarHidden = YES; 导航栏间出现动画突兀的问题

### ISSUE THREAD

**Issue by LINDreaming** [forkingdog/FDFullscreenPopGesture#206]
iOS 14设置 self.fd_prefersNavigationBarHidden = YES; 导航栏间出现动画突兀的问题
描述： 在iOS 14 A页面导航栏隐藏，B页面导航栏不隐藏，A设置self.fd_prefersNavigationBarHidden = YES； 在A->B 或者B->A 页面跳转的过程中，出现导航过渡动画的突兀，跳转页面在导航位置的颜色会一直显示一部分，直至另一个页面加载完全才消失；

**Comment by LINDreaming** [comment]
其他原因导致的，已修复

**Comment by yfming93** [comment]
> 

请问大佬。是什么原因导致的。我也出现了这个问题

**Comment by yfming93** [comment]
> 其他原因导致的，已修复

请问大佬。是什么原因导致的。我也出现了这个问题
