### ISSUE TITLE
请问这个涉及到私有API吗？苹果审核会拒绝吗？

### ISSUE THREAD

**Issue by cbahai** [forkingdog/FDFullscreenPopGesture#25]
请问这个涉及到私有API吗？苹果审核会拒绝吗？

**Comment by zhiliang729** [comment]
暂时没有被拒

**Comment by AngryLi** [comment]
那到底涉及到私有API吗？害怕哪天苹果抽风就悲剧了

**Comment by zhiliang729** [comment]
确实有私有api

发自我的 iPhone

**Comment by yangzhixiao** [comment]
这些作者不都已经在博客解释了嘛，百度知道APP就用了这个库，已经审核通过了，说明没有问题，放心使用吧

**Comment by CocodyChou** [comment]
哎哟，张良。

这个库，在使用自定义的转场动画时，会没有百分比效果，触发pop后会直接pop

发自我的 iPhone

**Comment by zhiliang729** [comment]
发布肯定没问题，我们的app也用了这个，发布正常

发自我的 iPhone

**Comment by YK-Unit** [comment]
已经有多个项目的APP使用了，暂时都没遇到被拒。

**Comment by afantree** [comment]
#88
