### ISSUE TITLE
与scrollview 的panGestureRecognizer 冲突

### ISSUE THREAD

**Issue by zhiliang729** [forkingdog/FDFullscreenPopGesture#27]
与scrollview 的panGestureRecognizer 冲突， 有没有判断的方法？

**Comment by zhiliang729** [comment]
找到了一个解决办法 我的scrollview里面是加了两个tableview的，故有如下解决方案
@interface UIScrollView (AllowPanGestureEventPass)
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer;
@end

@implementation UIScrollView (AllowPanGestureEventPass)

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    if (self.contentOffset.x < [UIScreen mainScreen].bounds.size.width && self.tag == 2989) {
        //            NSLog(@"view:%@", otherGestureRecognizer.view);
        if ([otherGestureRecognizer.view isKindOfClass:[UITableView class]] || [otherGestureRecognizer.view isKindOfClass:NSClassFromString(@"UITableViewWrapperView")]) {
            return NO;
        }else{
            return YES;
        }
    }else{
        return NO;
    }
}

@end

**Comment by afantree** [comment]
👍 good!
