### ISSUE TITLE
有个设置可恢复到默认的左滑返回就完美了！

### ISSUE THREAD

**Issue by syxc** [forkingdog/FDFullscreenPopGesture#36]
这个全屏滑动返回还是没法接受，有个设置可恢复到默认的左滑返回就完美了！

**Comment by JRJian** [comment]
vc 里面设置 self.fd_interactivePopMaxAllowedInitialDistanceToLeftEdge = 10.0f;
接近默认系统的左边可接受的滑动响应区

**Comment by syxc** [comment]
@JRJian 多谢提醒！
