### ISSUE TITLE
请问如何监听滑动返回手势的方法？

### ISSUE THREAD

**Issue by yaleidev** [forkingdog/FDFullscreenPopGesture#48]
当点击返回按钮的时候需要做事件操作，这个返回有调方法吗

**Comment by xushichen** [comment]
@yaleidev 解决了吗？如何监听返回

**Comment by afantree** [comment]
什么场景下需要监听？ 比如说？
用   `viewDidDisappear:`  或 `viewWillDisappear:`  解决不了 ?

**Comment by xushichen** [comment]
A页面push到B页面 
B返回需要通知A 
如果用`viewDidDisappear:`或`viewWillDisappear:` 会通知c 
现在只需要通知a
