### ISSUE TITLE
1.1返回时隐藏NavigationBar失效

### ISSUE THREAD

**Issue by ycge234** [forkingdog/FDFullscreenPopGesture#5]
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];

    // Do any additional setup after loading the view.
    [[self navigationController] setNavigationBarHidden:YES animated:YES];  //并没有卵用了
}

1.0测试了下没有问题。

**Comment by sunnyxx** [comment]
1.1 下最好使用我们这套 bar 控制流程，在你的 viewDidLoad 中：

``` objc
viewController.fd_prefersNavigationBarHidden = YES;
```

系统的控制代码就不用了

**Comment by ycge234** [comment]
貌似不行··我现在的界面是这样
navigationController->viewController->viewController(viewDidLoad:show, viewWillDisappear:hide)->viewController

**Comment by sunnyxx** [comment]
用我说的方法，只需要设置要隐藏bar的vc的这个属性，其他所有使用系统 API（`setNavigationBarHidden:animated:`） 来控制的代码都干掉试试看。
