### ISSUE TITLE
从无Bar到有Bar，来回滑动并取消，有Bar的页面导航栏消失了

### ISSUE THREAD

**Issue by lexiaoyao20** [forkingdog/FDFullscreenPopGesture#55]
貌似调用了 setNavigationBarHidden:animated: 就会有这个问题，不知道有什么办法修复没？？

**Comment by windylel** [comment]
你的情况是表现为导航栏消失了吗？我的有一定情况下导航栏会完全消失，那个位置变黑。

**Comment by lexiaoyao20** [comment]
我给你看下直观的效果图吧

![pop.gif](https://github.com/lexiaoyao20/SimplePieChart/blob/master/ScreenShots/pop.gif)

**Comment by lexiaoyao20** [comment]
终于研究出了一个不太完美的解决方案，体验上稍微差了点，但是总比导航栏消息了要好，代码如下，在无Bar的VC添加如下代码：
```
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.navigationController setNavigationBarHidden:YES animated:animated];
    });
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.navigationController setNavigationBarHidden:NO animated:animated];
    });
    
}
```

**Comment by jiyee** [comment]
想问下，这种情况是否添加一个隐藏的 navbar 而不是不设置能不能解决？

**Comment by TorchLennon** [comment]
参考楼上 
我的解决方法：
在隐藏导航栏的控制器
`- (void)viewWillDisappear:(BOOL)animated{
    [super viewWillDisappear:animated];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(CGFLOAT_MIN * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        UIViewController *vc = [self.navigationController.viewControllers lastObject];
        if (!vc.fd_prefersNavigationBarHidden) {
            [self.navigationController setNavigationBarHidden:NO animated:NO];
        }
    });
}`

**Comment by TorchLennon** [comment]
参考楼上 
我的解决方法：
在隐藏导航栏的控制器
```objectivec
- (void)viewWillDisappear:(BOOL)animated{
    [super viewWillDisappear:animated];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(CGFLOAT_MIN * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        UIViewController *vc = [self.navigationController.viewControllers lastObject];
        if (!vc.fd_prefersNavigationBarHidden) {
            [self.navigationController setNavigationBarHidden:NO animated:NO];
        }
    });
}
```

**Comment by lexiaoyao20** [comment]
@TorchLennon 这个比我的方案要好，完美解决问题。 果然群众的力量是无穷的
