### ISSUE TITLE
有水平方向滚动的ScrollView时边缘返回手势失效

### ISSUE THREAD

**Issue by jxaufang168** [forkingdog/FDFullscreenPopGesture#61]
有水平方向滚动的ScrollView时边缘返回手势失效,手势有冲突了。

**Comment by kinghudi** [comment]
我也碰到了 视图中装了一个可左右滑动的UIScrollView时 边缘返回失效了  请问如何解决

**Comment by afantree** [comment]
https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview
