### ISSUE TITLE
请问，Twitter那种有导航栏的返回动画效果怎么做的呢？

### ISSUE THREAD

**Issue by yaleidev** [forkingdog/FDFullscreenPopGesture#62]
请问，Twitter那种有导航栏的返回动画效果怎么做的呢？本级导航栏返回的时候（pop），跟上一级的导航栏感觉是独立的效果，这个支持吗？

**Comment by j364960953** [comment]
请问你们百度贴吧手势滑动返回的时候，导航栏跟随滚动是怎么设计的呢？可以说一下吗

**Comment by afantree** [comment]
This problem is best to goto  [stackoverflow](http://stackoverflow.com/)
Thanks !
