### ISSUE TITLE
能不能不碰私有API？

### ISSUE THREAD

**Issue by liuxuan30** [forkingdog/FDFullscreenPopGesture#7]
代码挺好，但是利用了私有API有点虚，万一审核人员较真就悲剧了，而且感觉就是个定时炸弹。技术上来说，有没可能绕开？

// 1. 私有变量标志transition动画是否正在进行
[self.navigationController valueForKey:@"_isTransitioning"];
// 2. 一个内部的selector
NSSelectorFromString(@"handleNavigationTransition:");

顺道问下，为啥需要者两个私有的API?

**Comment by DylanDu123** [comment]
回答楼上的问题，这两个私有API就是苹果控制系统的POP动画用的。
这个demo的实现思想就是用自己自定义的手势来替换掉苹果的手势。
同时让自己自定义的手势触发的方法和苹果的一样。

**Comment by liuxuan30** [comment]
不知道替换私有手势会不会出问题？纯探讨有没可能不需要替换来做。比如把系统手势禁掉，换上你的。

**Comment by DylanDu123** [comment]
如果按照你的需求的话需要自己把系统的返回动画自己全部重新实现一边。

**Comment by liuxuan30** [comment]
略苦逼。。多谢。
