### ISSUE TITLE
我擦swizzle

### ISSUE THREAD

**Issue by duanhjlt** [forkingdog/FDFullscreenPopGesture#74]
这是个好东西，好多轮子也都喜欢用，也确实能起到意想不到的效果。。。但是第三方库多了，这个东西就会很恶心，会有很对你意想不到的问题。。。。

个人觉得，整个项目有一个就够了，自己管理，不容出问题。可以让用户在你指定的地方主动调用你的方法。 

FDFullscreenPopGesture 的uiviewcontroller的load导致我们一些navigationController显示混乱。我只好把load都干掉，全部统一管理，这样一来，我就不能用pod了，真可惜。。。

**Comment by rickytan** [comment]
本人最近做了个新解决方案，有兴趣可以偿试一下：https://github.com/rickytan/RTRootNavigationController

**Comment by duanhjlt** [comment]
看了下效果，还不错。慢慢研究

**Comment by afantree** [comment]
Good idea
