### ISSUE TITLE
我发现有一个简单的办法

### ISSUE THREAD

**Issue by wu736139669** [forkingdog/FDFullscreenPopGesture#75]
可以直接kvc，实测过完全没问题，楼主以为UIScreenEdgePanGestureRecognizer这里面只有一个属性不能更改，其实里面有私有属性，用kvc就可以了，很方便哦。
[self.interactivePopGestureRecognizer setValue:@([UIScreen mainScreen].bounds.size.width) forKeyPath:@"_recognizer._settings._edgeSettings._edgeRegionSize"];

**Comment by VaeXnn** [comment]
有些有scrollview的怎么控制好让这个pan手势不冲突啊?

**Comment by wu736139669** [comment]
上面的那个方法就是用系统原来的，只是增大了区域，按照里面的会先对上层的scrollview滑动进行处理的，我实际操作也是那样

**Comment by leecade** [comment]
mark

**Comment by weiminghuaa** [comment]
Great Idea! 这个能通过审核吗？

**Comment by afantree** [comment]
https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview  .
