### ISSUE TITLE
控制器里面有ScrollView怎么进行侧滑返回？

### ISSUE THREAD

**Issue by SilenceZhou** [forkingdog/FDFullscreenPopGesture#90]

**Comment by mrhyh** [comment]
关闭ScrollView的左右滑动功能

**Comment by mrhyh** [comment]
关掉scrollView的左右滑动功能

**Comment by SilenceZhou** [comment]
由于需要进行 scrollview横向滚动几个界面，所以还是需要开启scrollview的侧滑的

**Comment by ssj1314** [comment]
http://www.jianshu.com/p/8170fea174da

**Comment by afantree** [comment]
https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview  .

**Comment by MrCaiWH** [comment]
@afantree 嗨，我的加了重新收拾的这个方法，还是不好使，还需要做别的事吗，求指导，谢谢
