### ISSUE TITLE
有没有属性方法实现，退出第二个界面，导航条是透明，但是导航条还在，第三个界面导航条又有颜色这种情况处理

### ISSUE THREAD

**Issue by XHJiang** [forkingdog/FDFullscreenPopGesture#93]

**Comment by Michaelyb520** [comment]
在Xcode 8下面编译，iOS9.2及9.2以下能正常运行吗？会不会直接崩掉并闪退？我这程序直接跑步起来了

**Comment by XHJiang** [comment]
我没用.没敢用,手动写的

**Comment by afantree** [comment]
@Michaelyb520   Maybe other reasons ? Is it solved now ?

**Comment by afantree** [comment]
@XHJiang Very good .   Special requirements require special implementation . Thanks !
