### ISSUE TITLE
解决ScrollView侧滑问题（兼容系统侧滑）

### ISSUE THREAD

**Issue by iosBob** [forkingdog/FDFullscreenPopGesture#94]
#1.修改方法fd_pushViewController中

```
// 修改点 NO->YES
    // Disable the onboard gesture recognizer.
    self.interactivePopGestureRecognizer.enabled = YES;
```
#2.新增代码到方法setFd_interactivePopDisabled
- (void)setFd_interactivePopDisabled:(BOOL)disabled
  {
  // 修改点
  if (self.navigationController) {
      self.navigationController.interactivePopGestureRecognizer.enabled = !disabled;
  }
  
  objc_setAssociatedObject(self, @selector(fd_interactivePopDisabled), @(disabled), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  }

**Comment by afantree** [comment]
Good idea ! 
We also can customize the scrollView or subclass of scrollView and overload the gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: method .
see  https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview
