### ISSUE TITLE
从无bar侧滑切到有bar，不美观

### ISSUE THREAD

**Issue by Xmanzn** [forkingdog/FDFullscreenPopGesture#98]
从无bar页面侧滑到有bar页面。有bar界面的bar紧贴着右边，而下面的视图控制器确是从中间开始的。查看了下内部的方法，找不准是哪个方法，你有办法解决么

**Comment by WTGrim** [comment]
从无tabBar到有tabBar我也感觉不美观，tarBar直接弹出了
